from . import views
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path("", views.index, name="index"),
    path("dashboard", views.dashboard, name="dashboard"),
    path("lead", views.lead, name="lead"),
    path("accounts", views.accounts, name="accounts"),
    path("customer", views.customer, name="customer"),
    path("edit_category_modal", views.edit_category_modal, name="edit_category_modal"),
    path("edit_product_modal", views.edit_product_modal, name="edit_product_modal"),
    path("register", views.register, name="register"),
    path("sub_company", views.sub_company, name="sub_company"),
    path("quotation", views.quotation, name="quotation"),
    path("edit_company_modal", views.edit_company_modal, name="edit_company_modal"),
    path("view_customer_details",views.view_customer_details,name="view_customer_details",
    ),
    path("inactive_company", views.inactive_company, name="inactive_company"),
    # path('account_details',views.account_details,name='account_details'),
    path("product_data", views.product_data, name="product_data"),
    path("login_action", views.login_action, name="login_action"),
    path("add_category_action", views.add_category_action, name="add_category_action"),
    path("add_product_action", views.add_product_action, name="add_product_action"),
    path("add_customer_action", views.add_customer_action, name="add_customer_action"),
    path("product_purchase_amount_view",views.product_purchase_amount_view,name="product_purchase_amount_view",),
    path("edit_category_action/<str:id>",views.edit_category_action,name="edit_category_action",),
    path("delete_category/<str:id>", views.delete_category, name="delete_category"),
    path("edit_product_action/<str:id>",views.edit_product_action,name="edit_product_action",),
    path("delete_product/<str:id>", views.delete_product, name="delete_product"),
    path("signup_action", views.signup_action, name="signup_action"),
    path("create_sub_company",views.create_sub_company,name="create_sub_company",),
    path("edit_subcompany_action/<str:id>",views.edit_subcompany_action,name="edit_subcompany_action",),
    path("logout_view", views.logout_view, name="logout_view"),
    path("delete_subcompany/<str:id>", views.delete_subcompany, name="delete_subcompany"),
    path("inactive_company_action/<str:id>",views.inactive_company_action,name="inactive_company_action",),
    path("delete_customer/<str:id>", views.delete_customer, name="delete_customer"),
    path("pdf", views.pdf, name="pdf"),
    path("category_search", views.category_search, name="category_search"),
    path("subcompany_search", views.subcompany_search, name="subcompany_search"),
    path("product_search", views.product_search, name="product_search"),
    path("customer_search", views.customer_search, name="customer_search"),
    path("send_html_to_pdf", views.send_html_to_pdf, name="send_html_to_pdf"),
    path("html_to_pdf", views.html_to_pdf, name="html_to_pdf"),
]
